package:
  name: pylp
  version: "0.2"

source:
  git_url: https://github.com/funkey/pylp
  git_rev: 474b164a2b19061fdf675a07b31c6975c0705a2e

build:
  number: 1

requirements:
 build:
   - {{ compiler('cxx') }}
 host:
   - cython
   - python {{python}}
   - scip
   - gurobi
 run:
   - python {{python}}
   - scip
   - gurobi

about:
  home: https://github.com/funkey/pylp
  license: MIT License
