package:
  name: pylp
  version: "0.1"

source:
  git_url: https://github.com/funkey/pylp
  git_rev: baa7585c4cac1394536f9861ca152549ca55160e

build:
  number: 2

requirements:
 build:
   - {{ compiler('cxx') }}
 host:
   - cython
   - python {{python}}
   - scip
   - gurobi
 run:
   - python {{python}}
   - scip
   - gurobi

about:
  home: https://github.com/funkey/pylp
  license: MIT License
