package:
  name: pylp
  version: "0.0.1"

source:
  git_url: https://github.com/funkey/pylp
  git_rev: bae725efa46d92121c9f8079c5286ac30ed9ebc1

build:
  number: 12

requirements:
 build:
   - cmake=3.3
   - gcc
   - libgcc
   - boost
   - py-boost
   - python {{python}}
 run:
   - libgcc
   - boost
   - py-boost
   - python {{python}}

about:
  home: https://github.com/funkey/pylp
  license: MIT License
