package:
  name: pylp
  version: "0.0.1"

source:
  git_url: https://github.com/funkey/pylp
  git_rev: 36d9616d4ff2c891bf5d5d418f8177b789b097b0

build:
  number: 14

requirements:
 build:
   - cmake=3.3
   - gcc
   - libgcc
   - boost
   - py-boost
   - python {{python}}
   - gurobi
 run:
   - libgcc
   - boost
   - py-boost
   - gurobi
   - python {{python}}

about:
  home: https://github.com/funkey/pylp
  license: MIT License
