package:
  name: pylp
  version: "0.1"

source:
  git_url: https://github.com/funkey/pylp
  git_rev: 3271a3916262d7c4e13f9fbb63a8c9ee8f9f676b

build:
  number: 1

requirements:
 build:
   - libgcc
   - python {{python}}
   - cython
   - scip
   - gurobi
 run:
   - libgcc
   - python {{python}}
   - scip
   - gurobi

about:
  home: https://github.com/funkey/pylp
  license: MIT License
