package:
  name: pylp
  version: "0.0.2"

source:
  git_url: https://github.com/funkey/pylp
  git_rev: 73f18651043558fc6a23cf645fbad907645087cf

build:
  number: 1

requirements:
 build:
   - cmake=3.3
   - gcc
   - libgcc
   - boost
   - py-boost
   - python {{python}}
   - gurobi
 run:
   - libgcc
   - boost
   - py-boost
   - gurobi
   - python {{python}}

about:
  home: https://github.com/funkey/pylp
  license: MIT License
