package:
  name: pylp
  version: "0.2"

source:
  git_url: https://github.com/funkey/pylp
  git_rev: 38592a62004a7dfad3ee4d3eccc802d4b21bfff1

build:
  number: 1

requirements:
 build:
   - {{ compiler('cxx') }}
 host:
   - cython
   - python {{python}}
   - scip
   - gurobi
 run:
   - python {{python}}
   - scip
   - gurobi

about:
  home: https://github.com/funkey/pylp
  license: MIT License
